In [1]:
from langchain_community.document_loaders import PyMuPDFLoader


pdf_path = "data/Indias_Ancient_history_full.pdf"
loader = PyMuPDFLoader(pdf_path)
documents = loader.load()
print(f"Pages loaded: {len(documents)}")

/var/folders/1f/dc6nbcvj0yzdh4mpnz5f_3l00000gn/T/ipykernel_87635/2781586893.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyMuPDFLoader
/Users/dipyaman/Documents/codes/genAI/RAG_practice/rag/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Pages loaded: 422

In [2]:
# Load opeanai api key from environment variable
import os
from dotenv import load_dotenv

load_dotenv()

open_api_key = os.environ.get("OPENAI_API_KEY")

langsmith_api_key = os.environ.get("LANGSMITH_API_KEY")
# os.environ["LANGSMITH_TRACING"] = "true"
# os.environ["LANGSMITH_PROJECT"] = "rag_eval_ancient"

In [4]:
print(documents[14].page_content)  # Print the first 500 characters of the first page

1
The Significance of
Ancient Indian History
The study of ancient Indian history is important for several reasons. It tells us
how, when, and where people developed the earliest cultures in India, how they
began undertaking agriculture and stock raising which made life secure and
settled. It shows how the ancient Indians discovered and utilized natural
resources, and how they created the means for their livelihood. We get an idea of
how the ancient inhabitants made arrangements for food, shelter, and transport,
and learn how they took to farming, spinning, weaving, metalworking, and the
like, how they cleared forests, founded villages, cities, and eventually large
kingdoms.
People are not considered civilized unless they know how to write. The
different forms of writing prevalent in India today are all derived from the
ancient scripts. This is also true of the languages that we speak today. The
languages we use have roots in ancient times, and have developed through the
ages.
Unity in Diversity
Ancient Indian history is interesting because many races and tribes intermingled
in early India. The pre-Aryans, the Indo-Aryans, the Greeks, the Scythians, the
Hunas, the Turks, and others made India their home. Each ethnic group
contributed its mite to the evolution of the Indian social system, art and
architecture, language and literature. All these peoples and their cultural traits
commingled so inextricably that currently they can be clearly identified in their

In [5]:
full_text = " ".join([doc.page_content for doc in documents])
full_text_shorten  = " ".join([doc.page_content for doc in documents[14:]]) # Skip the first 13 pages as they are not relevant to the chapters

In [6]:
import re
pattern = r"(\d+)\.\s*\n([^\n]+)"
matches = list(re.finditer(pattern, full_text))

In [7]:
matches = matches[:33]

In [8]:
chapters = []

for m in matches:  # Skip the first 33 matches
    print("Chapter:", m.group(1))
    print("Title:", m.group(2))
    print("-" * 50)
    chapters.append(m.group(2))  # Append the chapter title to the list

Chapter: 1
Title: The Significance of Ancient Indian History
--------------------------------------------------
Chapter: 2
Title: Modern Historians of Ancient India
--------------------------------------------------
Chapter: 3
Title: Nature of Sources and Historical Construction
--------------------------------------------------
Chapter: 4
Title: Geographical Setting
--------------------------------------------------
Chapter: 5
Title: Ecology and Environment
--------------------------------------------------
Chapter: 6
Title: The Linguistic Background
--------------------------------------------------
Chapter: 7
Title: Human Evolution: The Old Stone Age
--------------------------------------------------
Chapter: 8
Title: The Neolithic Age: First Food Producers and Animal Keepers
--------------------------------------------------
Chapter: 9
Title: Chalcolithic Cultures
--------------------------------------------------
Chapter: 10
Title: Harappan Culture: Bronze Age Urbanization in the Indus Valley
--------------------------------------------------
Chapter: 11
Title: Identity of Aryan Culture
--------------------------------------------------
Chapter: 12
Title: The Age of the Rig Veda
--------------------------------------------------
Chapter: 13
Title: The Later Vedic Phase: Transition to State and Social Orders
--------------------------------------------------
Chapter: 14
Title: Jainism and Buddhism
--------------------------------------------------
Chapter: 15
Title: Territorial States and the Rise of Magadha
--------------------------------------------------
Chapter: 16
Title: Iranian and Macedonian Invasions
--------------------------------------------------
Chapter: 17
Title: State Structure and the Varna System in the Age of the Buddha
--------------------------------------------------
Chapter: 18
Title: The Maurya Age
--------------------------------------------------
Chapter: 19
Title: The Significance of Maurya Rule
--------------------------------------------------
Chapter: 20
Title: Central Asian Contact and Mutual Impact
--------------------------------------------------
Chapter: 21
Title: The Satavahana Phase
--------------------------------------------------
Chapter: 22
Title: The Dawn of History in the Deep South
--------------------------------------------------
Chapter: 23
Title: Crafts, Commerce, and Urban Growth (200 BC–AD 250)
--------------------------------------------------
Chapter: 24
Title: Rise and Growth of the Gupta Empire
--------------------------------------------------
Chapter: 25
Title: Life in the Gupta Age
--------------------------------------------------
Chapter: 26
Title: Spread of Civilization in Eastern India
--------------------------------------------------
Chapter: 27
Title: Harsha and His Times Harsha’s Kingdom; Administration; Buddhism and Nalanda; Chronology
--------------------------------------------------
Chapter: 28
Title: Brahmanization, Rural Expansion, and Peasant Protest in the Peninsula
--------------------------------------------------
Chapter: 29
Title: Developments in Philosophy
--------------------------------------------------
Chapter: 30
Title: Cultural Interaction with Asian Countries
--------------------------------------------------
Chapter: 31
Title: From Ancient to Medieval
--------------------------------------------------
Chapter: 32
Title: Sequence of Social Changes
--------------------------------------------------
Chapter: 33
Title: Legacy in Science and Civilization
--------------------------------------------------

In [9]:
import re

positions = []

for chapter in chapters:

    pattern = re.escape(chapter)
    match = re.search(pattern, full_text_shorten.replace("\n"," "), re.IGNORECASE)

    if match:
        positions.append((chapter, match.start()))

In [10]:
chapters_text = []

for i in range(0,len(positions)):

    chapter_name, start = positions[i]

    if i < len(positions) - 1:
        end = positions[i + 1][1]
    else:
        end = len(full_text_shorten)

    text = full_text_shorten[start:end].strip()

    chapters_text.append({
        "chapter": chapter_name,
        "text": text
    })

In [11]:
# Create documents
from langchain_core.documents import Document

docs = []

for ch in chapters_text:
    docs.append(Document(page_content=ch['text'], metadata={"chapter": ch['chapter']}))

In [12]:
chapter_dict = {item: idx for idx, item in enumerate(chapters)}

In [13]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=150
)

chunks = splitter.split_documents(docs)

from collections import defaultdict

chapter_counter = defaultdict(int)


for i, chunk in enumerate(chunks):
    chapter = chunk.metadata['chapter']
    chapter_counter[chapter] += 1
    chapter_num = chapter_dict[chapter] + 1

    chunk.metadata['chapter_chunk'] = chapter_counter[chapter]
    chunk.metadata['chunk_label'] = f"{chapter}_{chapter_counter[chapter]}"
    chunk.metadata['chunk_level'] = f"Chapter{chapter_num}_{chapter_counter[chapter]}"

In [14]:
for chunk in chunks:  # Print metadata of the first 5 chunks
    print(chunk.metadata)
    print("-" * 50)

{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 1, 'chunk_label': 'The Significance of Ancient Indian History_1', 'chunk_level': 'Chapter1_1'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 2, 'chunk_label': 'The Significance of Ancient Indian History_2', 'chunk_level': 'Chapter1_2'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 3, 'chunk_label': 'The Significance of Ancient Indian History_3', 'chunk_level': 'Chapter1_3'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 4, 'chunk_label': 'The Significance of Ancient Indian History_4', 'chunk_level': 'Chapter1_4'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 5, 'chunk_label': 'The Significance of Ancient Indian History_5', 'chunk_level': 'Chapter1_5'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 6, 'chunk_label': 'The Significance of Ancient Indian History_6', 'chunk_level': 'Chapter1_6'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 7, 'chunk_label': 'The Significance of Ancient Indian History_7', 'chunk_level': 'Chapter1_7'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 8, 'chunk_label': 'The Significance of Ancient Indian History_8', 'chunk_level': 'Chapter1_8'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 9, 'chunk_label': 'The Significance of Ancient Indian History_9', 'chunk_level': 'Chapter1_9'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 10, 'chunk_label': 'The Significance of Ancient Indian History_10', 'chunk_level': 'Chapter1_10'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 11, 'chunk_label': 'The Significance of Ancient Indian History_11', 'chunk_level': 'Chapter1_11'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 12, 'chunk_label': 'The Significance of Ancient Indian History_12', 'chunk_level': 'Chapter1_12'}
--------------------------------------------------
{'chapter': 'The Significance of Ancient Indian History', 'chapter_chunk': 13, 'chunk_label': 'The Significance of Ancient Indian History_13', 'chunk_level': 'Chapter1_13'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 1, 'chunk_label': 'Modern Historians of Ancient India_1', 'chunk_level': 'Chapter2_1'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 2, 'chunk_label': 'Modern Historians of Ancient India_2', 'chunk_level': 'Chapter2_2'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 3, 'chunk_label': 'Modern Historians of Ancient India_3', 'chunk_level': 'Chapter2_3'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 4, 'chunk_label': 'Modern Historians of Ancient India_4', 'chunk_level': 'Chapter2_4'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 5, 'chunk_label': 'Modern Historians of Ancient India_5', 'chunk_level': 'Chapter2_5'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 6, 'chunk_label': 'Modern Historians of Ancient India_6', 'chunk_level': 'Chapter2_6'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 7, 'chunk_label': 'Modern Historians of Ancient India_7', 'chunk_level': 'Chapter2_7'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 8, 'chunk_label': 'Modern Historians of Ancient India_8', 'chunk_level': 'Chapter2_8'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 9, 'chunk_label': 'Modern Historians of Ancient India_9', 'chunk_level': 'Chapter2_9'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 10, 'chunk_label': 'Modern Historians of Ancient India_10', 'chunk_level': 'Chapter2_10'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 11, 'chunk_label': 'Modern Historians of Ancient India_11', 'chunk_level': 'Chapter2_11'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 12, 'chunk_label': 'Modern Historians of Ancient India_12', 'chunk_level': 'Chapter2_12'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 13, 'chunk_label': 'Modern Historians of Ancient India_13', 'chunk_level': 'Chapter2_13'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 14, 'chunk_label': 'Modern Historians of Ancient India_14', 'chunk_level': 'Chapter2_14'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 15, 'chunk_label': 'Modern Historians of Ancient India_15', 'chunk_level': 'Chapter2_15'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 16, 'chunk_label': 'Modern Historians of Ancient India_16', 'chunk_level': 'Chapter2_16'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 17, 'chunk_label': 'Modern Historians of Ancient India_17', 'chunk_level': 'Chapter2_17'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 18, 'chunk_label': 'Modern Historians of Ancient India_18', 'chunk_level': 'Chapter2_18'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 19, 'chunk_label': 'Modern Historians of Ancient India_19', 'chunk_level': 'Chapter2_19'}
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 20, 'chunk_label': 'Modern Historians of Ancient India_20', 'chunk_level': 'Chapter2_20'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 1, 'chunk_label': 'Nature of Sources and Historical Construction_1', 'chunk_level': 'Chapter3_1'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 2, 'chunk_label': 'Nature of Sources and Historical Construction_2', 'chunk_level': 'Chapter3_2'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 3, 'chunk_label': 'Nature of Sources and Historical Construction_3', 'chunk_level': 'Chapter3_3'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 4, 'chunk_label': 'Nature of Sources and Historical Construction_4', 'chunk_level': 'Chapter3_4'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 5, 'chunk_label': 'Nature of Sources and Historical Construction_5', 'chunk_level': 'Chapter3_5'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 6, 'chunk_label': 'Nature of Sources and Historical Construction_6', 'chunk_level': 'Chapter3_6'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 7, 'chunk_label': 'Nature of Sources and Historical Construction_7', 'chunk_level': 'Chapter3_7'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 8, 'chunk_label': 'Nature of Sources and Historical Construction_8', 'chunk_level': 'Chapter3_8'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 9, 'chunk_label': 'Nature of Sources and Historical Construction_9', 'chunk_level': 'Chapter3_9'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 10, 'chunk_label': 'Nature of Sources and Historical Construction_10', 'chunk_level': 'Chapter3_10'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 11, 'chunk_label': 'Nature of Sources and Historical Construction_11', 'chunk_level': 'Chapter3_11'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 12, 'chunk_label': 'Nature of Sources and Historical Construction_12', 'chunk_level': 'Chapter3_12'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 13, 'chunk_label': 'Nature of Sources and Historical Construction_13', 'chunk_level': 'Chapter3_13'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 14, 'chunk_label': 'Nature of Sources and Historical Construction_14', 'chunk_level': 'Chapter3_14'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 15, 'chunk_label': 'Nature of Sources and Historical Construction_15', 'chunk_level': 'Chapter3_15'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 16, 'chunk_label': 'Nature of Sources and Historical Construction_16', 'chunk_level': 'Chapter3_16'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 17, 'chunk_label': 'Nature of Sources and Historical Construction_17', 'chunk_level': 'Chapter3_17'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 18, 'chunk_label': 'Nature of Sources and Historical Construction_18', 'chunk_level': 'Chapter3_18'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 19, 'chunk_label': 'Nature of Sources and Historical Construction_19', 'chunk_level': 'Chapter3_19'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 20, 'chunk_label': 'Nature of Sources and Historical Construction_20', 'chunk_level': 'Chapter3_20'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 21, 'chunk_label': 'Nature of Sources and Historical Construction_21', 'chunk_level': 'Chapter3_21'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 22, 'chunk_label': 'Nature of Sources and Historical Construction_22', 'chunk_level': 'Chapter3_22'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 23, 'chunk_label': 'Nature of Sources and Historical Construction_23', 'chunk_level': 'Chapter3_23'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 24, 'chunk_label': 'Nature of Sources and Historical Construction_24', 'chunk_level': 'Chapter3_24'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 25, 'chunk_label': 'Nature of Sources and Historical Construction_25', 'chunk_level': 'Chapter3_25'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 26, 'chunk_label': 'Nature of Sources and Historical Construction_26', 'chunk_level': 'Chapter3_26'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 27, 'chunk_label': 'Nature of Sources and Historical Construction_27', 'chunk_level': 'Chapter3_27'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 28, 'chunk_label': 'Nature of Sources and Historical Construction_28', 'chunk_level': 'Chapter3_28'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 29, 'chunk_label': 'Nature of Sources and Historical Construction_29', 'chunk_level': 'Chapter3_29'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 30, 'chunk_label': 'Nature of Sources and Historical Construction_30', 'chunk_level': 'Chapter3_30'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 31, 'chunk_label': 'Nature of Sources and Historical Construction_31', 'chunk_level': 'Chapter3_31'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 32, 'chunk_label': 'Nature of Sources and Historical Construction_32', 'chunk_level': 'Chapter3_32'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 33, 'chunk_label': 'Nature of Sources and Historical Construction_33', 'chunk_level': 'Chapter3_33'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 34, 'chunk_label': 'Nature of Sources and Historical Construction_34', 'chunk_level': 'Chapter3_34'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 35, 'chunk_label': 'Nature of Sources and Historical Construction_35', 'chunk_level': 'Chapter3_35'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 36, 'chunk_label': 'Nature of Sources and Historical Construction_36', 'chunk_level': 'Chapter3_36'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 37, 'chunk_label': 'Nature of Sources and Historical Construction_37', 'chunk_level': 'Chapter3_37'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 38, 'chunk_label': 'Nature of Sources and Historical Construction_38', 'chunk_level': 'Chapter3_38'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 39, 'chunk_label': 'Nature of Sources and Historical Construction_39', 'chunk_level': 'Chapter3_39'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 40, 'chunk_label': 'Nature of Sources and Historical Construction_40', 'chunk_level': 'Chapter3_40'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 41, 'chunk_label': 'Nature of Sources and Historical Construction_41', 'chunk_level': 'Chapter3_41'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 42, 'chunk_label': 'Nature of Sources and Historical Construction_42', 'chunk_level': 'Chapter3_42'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 43, 'chunk_label': 'Nature of Sources and Historical Construction_43', 'chunk_level': 'Chapter3_43'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 44, 'chunk_label': 'Nature of Sources and Historical Construction_44', 'chunk_level': 'Chapter3_44'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 45, 'chunk_label': 'Nature of Sources and Historical Construction_45', 'chunk_level': 'Chapter3_45'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 46, 'chunk_label': 'Nature of Sources and Historical Construction_46', 'chunk_level': 'Chapter3_46'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 47, 'chunk_label': 'Nature of Sources and Historical Construction_47', 'chunk_level': 'Chapter3_47'}
--------------------------------------------------
{'chapter': 'Nature of Sources and Historical Construction', 'chapter_chunk': 48, 'chunk_label': 'Nature of Sources and Historical Construction_48', 'chunk_level': 'Chapter3_48'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 1, 'chunk_label': 'Geographical Setting_1', 'chunk_level': 'Chapter4_1'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 2, 'chunk_label': 'Geographical Setting_2', 'chunk_level': 'Chapter4_2'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 3, 'chunk_label': 'Geographical Setting_3', 'chunk_level': 'Chapter4_3'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 4, 'chunk_label': 'Geographical Setting_4', 'chunk_level': 'Chapter4_4'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 5, 'chunk_label': 'Geographical Setting_5', 'chunk_level': 'Chapter4_5'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 6, 'chunk_label': 'Geographical Setting_6', 'chunk_level': 'Chapter4_6'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 7, 'chunk_label': 'Geographical Setting_7', 'chunk_level': 'Chapter4_7'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 8, 'chunk_label': 'Geographical Setting_8', 'chunk_level': 'Chapter4_8'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 9, 'chunk_label': 'Geographical Setting_9', 'chunk_level': 'Chapter4_9'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 10, 'chunk_label': 'Geographical Setting_10', 'chunk_level': 'Chapter4_10'}
--------------------------------------------------
{'chapter': 'Geographical Setting', 'chapter_chunk': 11, 'chunk_label': 'Geographical Setting_11', 'chunk_level': 'Chapter4_11'}
--------------------------------------------------

In [15]:
for chunk in chunks:
    if chunk.metadata["chapter"] == 'From Ancient to Medieval':
        print(chunk.metadata['chapter_chunk'])
        print(chunk.page_content)

1
from ancient to medieval
times. Harsha governed his empire on the same lines as did the Guptas, but his
administration had become feudal and decentralized. It is stated that Harsha had
100,000 horses and 60,000 elephants. This appears astonishing because the
Mauryas, who ruled over virtually the entire country except the deep south,
maintained only 30,000 cavalry and 9000 elephants. Harsha could have had a
larger army only if he was in a position to mobilize the support of all his
feudatories in the time of war. Evidently every feudatory contributed his quota of
foot soldiers and horses, and thus enormously added to the imperial army. The vast numbers of the imperial army suggests a great increase in population.
Land grants continued to be made to priests for special services rendered to
the state. More importantly, Harsha is credited with the grant of land to the
officers by issuing charters. These grants allowed the same concessions to priests
2
officers by issuing charters. These grants allowed the same concessions to priests
as were allowed by the earlier grants. The Chinese pilgrim Hsuan Tsang informs
us that Harsha’s revenues were divided into four parts. One part was earmarked
for the expenditure of the king, a second for scholars, a third for the endowment
of officials and public servants, and a fourth for religious purposes. He also tells
us that ministers and high officers of the state were endowed with land. The
feudal practice of rewarding and paying officers with grants of land seems to
have begun under Harsha. This explains why we do not have very many coins
issued by this king.
In Harsha’s empire, law and order was not well maintained. Hsuan Tsang,
about whose welfare, special care may have been taken by the government, was
robbed of his belongings, although he reports that according to the laws of the
land, severe punishments were inflicted for crime. Robbery was considered to be
3
land, severe punishments were inflicted for crime. Robbery was considered to be
a second treason for which the right hand of the robber was amputated. It
however appears that, under the influence of Buddhism, the severity of
punishment was mitigated and criminals were imprisoned for life.
The reign of Harsha is historically important because of the visit of the
Chinese pilgrim Hsuan Tsang, who left China in AD 629 and travelled all the way
to India. After a long stay in India, he returned to China in AD 645. He had come
to study at the Buddhist university of Nalanda situated in the district of the same
name in Bihar and to collect Buddhist texts from India. The pilgrim spent many
years in Harsha’s court and travelled widely in India. Under his influence Harsha
became a great supporter of Buddhism and made generous endowments to it.
The pilgrim vividly describes Harsha’s court and life in those days, and this
4
The pilgrim vividly describes Harsha’s court and life in those days, and this
account is richer and more reliable than that of Fa-hsien, shedding light on the
social and economic life as well as the religious sects of the period.
The Chinese account shows that Pataliputra was in a state of decline, as was
Vaishali. On the other hand, Prayag and Kanauj in the doab had become
important. The brahmanas and kshatriyas are reported to have led a simple life,
but the nobles and priests led a luxurious life. This indicates differentiation in the
ranks of each of the two higher varnas. The majority in each of them may have
taken to agriculture. Hsuan Tsang calls the shudras agriculturists, which is
significant. The earlier texts represent them as serving the three higher varnas.
The Chinese pilgrim notes the living conditions of the untouchables such as
5
The Chinese pilgrim notes the living conditions of the untouchables such as
scavengers, and executioners. The untouchables lived outside the villages, and ate garlic and onion, and when they entered the town, they announced their entry
by shouting loudly so that people might keep away from them.
Buddhism and Nalanda
The Buddhists were divided into eighteen sects when the Chinese pilgrim was in
India. The old centres of Buddhism had fallen on bad days. The most famous
centre was Nalanda, which maintained a great Buddhist university meant for
Buddhist monks. It is said to have had as many as 10,000 students, all monks.
They were taught Buddhist philosophy of the Mahayana school. Although all the
mounds of Nalanda have not been dug, excavations have exposed a very
impressive complex of buildings. These were raised and renovated over a period
of 700 years from the fifth century onwards. The buildings exposed by
excavations do not have the capacity to accommodate 10,000 monks. In AD 670,
6
of 700 years from the fifth century onwards. The buildings exposed by
excavations do not have the capacity to accommodate 10,000 monks. In AD 670,
another Chinese pilgrim, I-tsing, visited Nalanda, and he mentions that only
3000 monks lived there. This is reasonable because, even if the remaining
mounds are excavated, the buildings cannot have been sufficiently spacious to
have accommodated 10,000 monks. According to Hsuan Tsang, the monastery at
Nalanda was supported from the revenues of 100 villages. I-tsing raises this
number to 200. Nalanda thus had a huge monastic establishment during the reign
of Harshavardhana.
Harsha followed a tolerant religious policy. A Shaiva in his early years, he
gradually became a great patron of Buddhism. As a devout Buddhist he
convened a grand assembly at Kanauj to widely publicize the doctrines of
Mahayana. The assembly was attended not only by Hsuan Tsang and the
Kamarupa ruler Bhaskaravarman, but also by the kings of twenty states and by
7
Mahayana. The assembly was attended not only by Hsuan Tsang and the
Kamarupa ruler Bhaskaravarman, but also by the kings of twenty states and by
several thousand priests belonging to different sects. Two thatched halls were
built to accommodate 1000 persons each. However, the most important
construction was a huge tower in the middle of which a golden statue of the
Buddha, as tall as the king himself, was placed. Harsha worshipped the image
and gave a public dinner. The discussion in the conference was initiated by
Hsuan Tsang who dilated on the virtues of Mahayana Buddhism and challenged
the audience to refute his arguments. However, nobody came forward for five
days, and then his theological rivals conspired to take the pilgrim’s life. Hearing
of this plot, Harsha threatened to behead anybody causing Hsuan Tsang the
slightest harm. Suddenly the great tower caught fire and there was an attempt to
assassinate Harsha. Harsha then arrested 500 brahmanas. He banished most of
8
assassinate Harsha. Harsha then arrested 500 brahmanas. He banished most of
them, and also executed a few. This would indicate that Harsha was not as tolerant as he is painted. After Kanauj, he held at Prayag a great assembly which
was attended by all the tributary princes, ministers, nobles, etc. On this occasion,
an image of the Buddha was worshipped, and discourses were given by Hsuan
Tsang. At the end of it, Harsha made huge donations, and according to a
tradition, he gave away everything except his personal clothing. Hsuan Tsang
speaks of Harsha in glowing terms. The king was kind, courteous, and helpful to
him, and the pilgrim was able to visit the various parts of the empire.
Banabhatta gives us a flattering account of the early years of his patron in his
book Harshacharita in an ornate style which became a model for later writers.
Harsha is remembered not only for his patronage and learning but also for the
9
Harsha is remembered not only for his patronage and learning but also for the
authorship of three plays: Priyadarshika, Ratnavali, and Nagananda. Bana
attributes great poetical skill to him, and some later authors consider him to have
been a literary monarch. However, Harsha’s authorship of the three dramas is
doubted by several medieval scholars. It is held that they were composed by a
person called Dhavaka in the name of Harsha for some consideration. Harsha
may have composed some pieces, but the proverb goes that royal authors are
only half authors. In both ancient and medieval India, various achievements,
including high literary attainments, were ascribed to a king in order to boost his
image. The practice of praising the patron initiated by Harishena in the time of
Samudragupta became common and well established under Harsha. Evidently,
the object in such cases was not only to win the favour of the king but also to
10
the object in such cases was not only to win the favour of the king but also to
validate and exalt his position in the eyes of his rivals and subjects.
Chronology
(AD)

5 C
Foundation of the Buddhist structural complex at
Nalanda. Establishment of white Huna supremacy over
Kashmir, Punjab, and western India.
6 C
The Guptas ruled over north and western India for
about 160 years until the middle of the century.
606–47
The reign of Harshavardhana.
629
Hsuan Tsang left China for India.
645
Hsuan Tsang’s return to China.
670
The Chinese pilgrim I-tsing visited Nalanda.
7 C
Harshacharita by Banabhatta and Hsuan Tsang’s
account. 28
Brahmanization, Rural Expansion,
and Peasant Protest in the Peninsula
The New Phase
The period c. AD 300–750 marks the second historical phase in the regions south
of the Vindhyas. It continued some of the processes that had begun in the first
historical phase (c. 200 BC–AD 300) of the peninsula. It however shows some
11
historical phase (c. 200 BC–AD 300) of the peninsula. It however shows some
new features that were not regarded as significant in earlier times. The first
phase shows the ascendancy of the Satavahanas over the Deccan, and that of the
Tamil kingdoms over the southern districts of Tamil Nadu. In that period,
northern Tamil Nadu, southern Karnataka, a part of southern Maharashtra, and
the land between the Godavari and the Mahanadi broadly owed allegiance to the
seats of political authority established outside their areas. They themselves did
not have their own states. Now in these areas and also in Vidarbha, between AD
300 and 600 there arose about two dozen states which are known to us from their
land charters. Eventually, by the beginning of the seventh century, the Pallavas
of Kanchi, the Chalukyas of Badami, and the Pandyas of Madurai emerged as
the rulers of the three major states. The first historical phase is marked by
12
the rulers of the three major states. The first historical phase is marked by
numerous crafts, internal and external trade, widespread use of coins, and a large
number of towns. Trade, towns, and coinage seem to have been in a state of
decline in the second phase, but in that phase numerous land grants free of taxes
were made to the temples and brahmanas. The grants suggest that many new
areas were brought under cultivation and settlement. This period therefore saw a
far greater expansion of agrarian economy.
We also notice the march of triumphant Brahmanism. In the first phase we
encounter extensive Buddhist monuments in both Andhra and Maharashtra. Cave inscriptions probably indicate the influence of Jainism and also of
Buddhism in the southern districts of Tamil Nadu. Now however Jainism was
confined to Karnataka, and the peninsula as a whole shows numerous instances
of the performance of Vedic sacrifices by the kings. This phase also marked the
13
of the performance of Vedic sacrifices by the kings. This phase also marked the
beginning of the construction of stone temples for Shiva and Vishnu in Tamil
Nadu under the Pallavas, and in Karnataka under the Chalukyas of Badami. By
the beginning of the second phase, south India had ceased to be the land of
megaliths, and towards its end began the process that made it a land of temples.
Culturally, the Dravidian element seems to have dominated the scene in the
first phase, but during the second phase Aryanization and brahmanization came
to the fore. This happened because of land grants made by the rulers who were
either brahmanas or firm supporters of them. As managers of temple lands, the
brahmanas guided cultural and religious activities. They spread Sanskrit, which
became the official language. The Ashokan inscriptions found in Andhra and
Karnataka show that the people knew Prakrit in the third century BC. Also,
14
became the official language. The Ashokan inscriptions found in Andhra and
Karnataka show that the people knew Prakrit in the third century BC. Also,
epigraphs between the second century BC and the third century AD were largely
written in Prakrit. The Brahmi inscriptions that have been found in Tamil Nadu
also contain Prakrit words, but from about AD 400 onwards Sanskrit became the
official language in the peninsula and most charters were composed in it.
States of the Deccan and South India
In northern Maharashtra and Vidarbha (Berar), the Satavahanas were succeeded
by the Vakatakas, a local power. The Vakatakas, who were brahmanas
themselves, are known from a large number of copperplate land grants issued by
them. They were great champions of the brahmanical religion and performed
numerous Vedic sacrifices. Their political history is more linked to north India
than to south India. We may recall how Chandragupta II married his daughter
15
than to south India. We may recall how Chandragupta II married his daughter
Prabhavati Gupta into the Vakataka royal family and with its support conquered
Malwa and Gujarat from the Shaka Kshatrapas in the last quarter of the fourth
century AD. Culturally however the Vakataka kingdom served as a channel for
the transmission of brahmanical ideas and social institutions to the south.
The Vakataka power was followed by that of the Chalukyas of Badami who
played an important role in the history of the Deccan and south India for about
two centuries until AD 757, when they were overthrown by their feudatories, the
Rashtrakutas. The Chalukyas claimed their descent from Brahma or Manu or the
Moon. They boasted that their ancestors ruled at Ayodhya, but all this was done to acquire legitimacy and respectability. In actuality they seem to have been a
local Kanarese people who were accommodated in the ruling varna with
brahmanical blessings.
16
local Kanarese people who were accommodated in the ruling varna with
brahmanical blessings.
The Chalukyas set up their kingdom towards the beginning of the sixth
century in the western Deccan. They established their capital at Vatapi, modern
Badami, in the district of Bijapur, which forms a part of Karnataka. They later
branched off into several independent ruling houses, but the main branch
continued to rule at Vatapi for two centuries. During this period, no other power
in the Deccan was as important as the Chalukyas of Badami until we come to
Vijayanagar in later medieval times.
On the ruins of the Satavahana power in the eastern part of the peninsula,
there arose the Ikshvakus in the Krishna–Guntur region. They seem to have been
a local tribe who adopted the exalted name of the Ikshvakus in order to
demonstrate the antiquity of their lineage, and also claimed to be brahmanas.
They have left behind many monuments at Nagarjunakonda and Dharanikota.
17
demonstrate the antiquity of their lineage, and also claimed to be brahmanas.
They have left behind many monuments at Nagarjunakonda and Dharanikota.
They began the practise of land grants in the Krishna–Guntur region, where
several of their copperplate inscriptions have been discovered.
The Ikshvakus were supplanted by the Pallavas. The term pallava means
creeper, and is a Sanskrit version of the Tamil word tondai, which also carries
the same meaning. The Pallavas were possibly a local tribe who established their
authority in the Tondainadu or the land of creepers. It however took them some
time to become completely civilized and acceptable because in Tamil, the word
pallava is also a synonym of robber. The authority of the Pallavas extended over
both southern Andhra and northern Tamil Nadu. They set up their capital at
Kanchi, identical with modern Kanchipuram, which under them became a town
of temples and Vedic learning.
18
Kanchi, identical with modern Kanchipuram, which under them became a town
of temples and Vedic learning.
The early Pallavas came into conflict with the Kadambas, who had
established their control over northern Karnataka and Konkan in the fourth
century. They claimed to be brahmanas, and generously rewarded their fellow
caste men.
The Kadamba kingdom was founded by Mayurasharman. It is said that he
came to receive education at Kanchi but was unceremoniously driven out.
Smarting under this insult, the Kadamba chief set up his camp in a forest, and
defeated the Pallavas, possibly with the help of the forest tribes. Eventually, the
Pallavas avenged the defeat but recognized the Kadamba authority by formally
investing Mayurasharman with the royal insignia. Mayurasharman is said to
have performed eighteen ashvamedhas or horse sacrifices and granted numerous
villages to brahmanas. The Kadambas established their capital at Vaijayanti or Banavasi in north Kanara district of Karnataka.
19
villages to brahmanas. The Kadambas established their capital at Vaijayanti or Banavasi in north Kanara district of Karnataka.
The Gangas were another important contemporary dynasty of the Pallavas.
They established their kingdom in southern Karnataka around the fourth century.
The kingdom was situated between that of the Pallavas in the east and of the
Kadambas in the west. They are called the Western Gangas or Gangas of Mysore
in order to differentiate them from the Eastern Gangas who ruled in Kalinga
from the fifth century onwards. For most of their reign, the Western Gangas were
feudatories of the Pallavas. Their earliest capital was located at Kolar which,
given its gold mines, may have helped the rise of this dynasty.
The Western Gangas made land grants mostly to the Jainas; the Kadambas
also made grants to the Jainas, though they favoured the brahmanas more. The
Pallavas for their part granted numerous villages free of taxes largely to the
20
Pallavas for their part granted numerous villages free of taxes largely to the
brahmanas. We have as many as sixteen land charters of the early Pallavas. A
few, which seem to be earlier, are written on stone in Prakrit, but most of them
were recorded on copperplates in Sanskrit. The villages granted to the
brahmanas were exempted from payment of all taxes and forced labour to the
state. This implied that these were collected from the cultivators by the
brahmanas for their personal use and profit. As many as eighteen types of
immunities were granted to the brahmanas in a Pallava grant of the fourth
century. They were empowered to enjoy the fruits of the land so granted and
exempted from payment of land tax, from supply of forced labour, from supply
of provisions to royal officers living in the town, and free from the interference
of royal agents and constabulary.
The Pallavas, the Kadambas, the Chalukyas of Badami, and their other
21
of royal agents and constabulary.
The Pallavas, the Kadambas, the Chalukyas of Badami, and their other
contemporaries were great champions of Vedic sacrifices. They performed
ashvamedha and vajapeya sacrifices, which legitimatized their position,
enhanced their prestige, and enormously increased the income of the priestly
class. The brahmanas therefore emerged as an important class at the expense of
the peasantry, from whom they collected their dues directly. They also received
as gifts a substantial proportion of the taxes collected by the king from his
subjects.
The Kalabhra Revolt
Although the period between AD 300 and 750 was extremely important for state
formation and agrarian expansion in the peninsula, very little is known about
what happened at the tip of the peninsula after the eclipse of the Cholas, the Cheras, and the Pandyas. The only important event is a revolt led by the

In [16]:
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en-v1.5"
)
vectorstore = FAISS.from_documents(chunks, embeddings)

/var/folders/1f/dc6nbcvj0yzdh4mpnz5f_3l00000gn/T/ipykernel_87635/2296132079.py:5: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5962.20it/s]

In [17]:
query = "What is the largest Buddhist temple in the world?"

results = vectorstore.similarity_search(query, k=5)

for r in results:
    print(r.metadata)
    print(r.page_content)
    print("-"*50)

{'chapter': 'From Ancient to Medieval', 'chapter_chunk': 59, 'chunk_label': 'From Ancient to Medieval_59', 'chunk_level': 'Chapter31_59'}
of a happy blending of both Indian and indigenous elements. It is astonishing
that the greatest Buddhist temple is to be found not in India but in Borobudur in
Java. Considered to be the largest Buddhist temple in the world, it was
constructed in the eighth century, and 436 images of the Buddha engraved on it
illustrate his life.
The temple of Ankor Vat in Cambodia is larger than that of Borobudur.
Although this temple dates to medieval times, it can be compared to the best
artistic achievements of the Egyptians and Greeks. The stories of the Ramayana
and Mahabharata are narrated in relief on the walls of the temple. The story of
the Ramayana is so popular in Indonesia that many folk plays based on it are
performed. The language of Indonesia, Bahasa Indonesia, contains numerous
Sanskrit words.
Cultural Give and Take
With regard to sculpture, the head of the Buddha from Thailand, the head from
Kamboja, and the magnificent bronze images from Java are regarded as the best
--------------------------------------------------
{'chapter': 'Spread of Civilization in Eastern India', 'chapter_chunk': 34, 'chunk_label': 'Spread of Civilization in Eastern India_34', 'chunk_level': 'Chapter26_34'}
number to 200. Nalanda thus had a huge monastic establishment during the reign
of Harshavardhana.
Harsha followed a tolerant religious policy. A Shaiva in his early years, he
gradually became a great patron of Buddhism. As a devout Buddhist he
convened a grand assembly at Kanauj to widely publicize the doctrines of
Mahayana. The assembly was attended not only by Hsuan Tsang and the
Kamarupa ruler Bhaskaravarman, but also by the kings of twenty states and by
several thousand priests belonging to different sects. Two thatched halls were
built to accommodate 1000 persons each. However, the most important
construction was a huge tower in the middle of which a golden statue of the
Buddha, as tall as the king himself, was placed. Harsha worshipped the image
and gave a public dinner. The discussion in the conference was initiated by
Hsuan Tsang who dilated on the virtues of Mahayana Buddhism and challenged
the audience to refute his arguments. However, nobody came forward for five
--------------------------------------------------
{'chapter': 'From Ancient to Medieval', 'chapter_chunk': 54, 'chunk_label': 'From Ancient to Medieval_54', 'chunk_level': 'Chapter31_54'}
Huang, which was the starting point of the companies of merchants crossing the
desert. The Indians learnt the art of growing silk from China, and the Chinese
learnt from India the art of Buddhist painting.
The two other great centres of Buddhism in ancient times were Afghanistan
and Central Asia. In Afghanistan, many statues of the Buddha and Buddhist
monasteries have been discovered. Begram and Bamiyan situated in the north of
this country are famous for such relics. Begram is famous for ivory work, which
is similar to Indian workmanship in Kushan times. Bamiyan had the distinction
of boasting of the tallest Buddha statue sculptured out of rock in the early
centuries of the Christian era; unfortunately this was recently destroyed by
aggressive, fundamentalist Afghan Muslims. Bamiyan has thousands of natural
and artificial caves in which the monks lived. Buddhism continued to hold its
ground in Afghanistan until the seventh century when it was supplanted by
Islam.
--------------------------------------------------
{'chapter': 'Spread of Civilization in Eastern India', 'chapter_chunk': 33, 'chunk_label': 'Spread of Civilization in Eastern India_33', 'chunk_level': 'Chapter26_33'}
Buddhist monks. It is said to have had as many as 10,000 students, all monks.
They were taught Buddhist philosophy of the Mahayana school. Although all the
mounds of Nalanda have not been dug, excavations have exposed a very
impressive complex of buildings. These were raised and renovated over a period
of 700 years from the fifth century onwards. The buildings exposed by
excavations do not have the capacity to accommodate 10,000 monks. In AD 670,
another Chinese pilgrim, I-tsing, visited Nalanda, and he mentions that only
3000 monks lived there. This is reasonable because, even if the remaining
mounds are excavated, the buildings cannot have been sufficiently spacious to
have accommodated 10,000 monks. According to Hsuan Tsang, the monastery at
Nalanda was supported from the revenues of 100 villages. I-tsing raises this
number to 200. Nalanda thus had a huge monastic establishment during the reign
of Harshavardhana.
--------------------------------------------------
{'chapter': 'From Ancient to Medieval', 'chapter_chunk': 6, 'chunk_label': 'From Ancient to Medieval_6', 'chunk_level': 'Chapter31_6'}
of 700 years from the fifth century onwards. The buildings exposed by
excavations do not have the capacity to accommodate 10,000 monks. In AD 670,
another Chinese pilgrim, I-tsing, visited Nalanda, and he mentions that only
3000 monks lived there. This is reasonable because, even if the remaining
mounds are excavated, the buildings cannot have been sufficiently spacious to
have accommodated 10,000 monks. According to Hsuan Tsang, the monastery at
Nalanda was supported from the revenues of 100 villages. I-tsing raises this
number to 200. Nalanda thus had a huge monastic establishment during the reign
of Harshavardhana.
Harsha followed a tolerant religious policy. A Shaiva in his early years, he
gradually became a great patron of Buddhism. As a devout Buddhist he
convened a grand assembly at Kanauj to widely publicize the doctrines of
Mahayana. The assembly was attended not only by Hsuan Tsang and the
Kamarupa ruler Bhaskaravarman, but also by the kings of twenty states and by
--------------------------------------------------

In [74]:

query = "What is the largest Buddhist temple in the world?"
from langsmith import traceable
retriever = vectorstore.as_retriever(
search_type="similarity",
search_kwargs={"k": 5}
)


@traceable
def generate_answer(query):
        # results = vectorstore.similarity_search(query, k=5)

        results = retriever.invoke(query)

        context = "\n".join([r.page_content for r in results])

        prompt = f"""
        You are a helpful teacher of Indian history. Answer the query ONLY based on provided context.
        Also put next line after every 100 characters in your answer. 
        If the answer is not present in the context, say "I don't know".
        Keep the output concise and suitable for a academic scholar in history.
        Context:{context}
        Query: {query}
        Answer:
        """

        from openai import OpenAI
        from langchain_openai import ChatOpenAI

        # client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
        llm = ChatOpenAI(model='gpt-4o-mini')
        response = llm.invoke(input=prompt,temperature=0.5)
        # response = client.responses.create(model='gpt-4o-mini',
                # input = prompt,
                # temperature=0.4
                # # max_output_tokens=500,
                # )
        
        return response.content

In [50]:
# test langsmith tracing
answer = generate_answer("What is the largest Buddhist temple in the world?")

# Evaluation of LLM
## First part evaluation of Retrieval:
### 1. Recall@K
### 2. MRR (Mean Reciprocal Rank)

In [20]:
# Read the golden answer from the file
import pandas as pd
golden_df = pd.read_excel("data/golden_data_ancient.xlsx")
# golden_df =  #.set_index('Question')
golden_df['Gold_Chunk'] = golden_df['Gold_Chunk'].str.split(',')  # Strip comma from the golden chunk
display(golden_df.head())

,ID,Question,Ground Truth Chunk,Reference Answer,Gold_Chunk
0,1,Why is it important to study the history of An...,Chapter_1,The study of ancient Indian history is importa...,[Chapter1_1]
1,2,What was the role of Sir William Jones?,Chapter_2,Sir William Jones was a civil servant of East ...,"[Chapter2_1, Chapter2_2]"
2,3,How did the Rationalist approach the History?,Chapter_2,A section of the Indian scholars tries to refo...,"[Chapter2_7, Chapter2_8, Chapter2_17]"
3,4,Who was Ramakrishna Gopal Bhandarkar and what ...,Chapter_2,Ramakrishna Gopal Bhandarkar was a Indian Hist...,"[Chapter2_8, Chapter2_9]"
4,5,How are prehistoric sites are different from h...,Chapter_3,There are several difference between prehistor...,[Chapter3_1]

In [21]:
# Extract the retrieved chunks and the ranks from the retrieval results (Sample)

query = "What was the role of Sir William Jones?"

results = retriever.invoke(query, k=5)

for r in results:
    print(r.metadata)
    print(r.page_content)
    print("-"*50)

{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 2, 'chunk_label': 'Modern Historians of Ancient India_2', 'chunk_level': 'Chapter2_2'}
until the eighteenth century, culminated in the establishment in Calcutta in 1784
of the Asiatic Society of Bengal. It was set up by a civil servant of the East India
Company, Sir William Jones (1746–94). He was the first to suggest that Sanskrit,
Latin, and Greek belonged to the same family of languages. He also translated
the play known as the Abhijnanashakuntalam into English in 1789; the
Bhagvadgita, the most popular Hindu religious text was translated into English
by Wilkins in 1785. The Bombay Asiatic Society was set up in 1804, and the
Asiatic Society of Great Britain was set up in London in 1823. William Jones
emphasized that originally the European languages were very similar to Sanskrit
and the Iranian language. This enthused European countries such as Germany,
France, and Russia, to foster Indological studies. During the first half of the
nineteenth century, chairs in Sanskrit were established in the UK and several
--------------------------------------------------
{'chapter': 'The Maurya Age', 'chapter_chunk': 18, 'chunk_label': 'The Maurya Age_18', 'chunk_level': 'Chapter18_18'}
missionaries were sent not only to south India but also to Sri Lanka, Myanmar
(Burma), and other countries to convert the people there. Brahmi inscriptions of
the second and first centuries BC have been found in Sri Lanka.
Ashoka set a very high ideal for himself, and this was the ideal of paternal
kingship. He repeatedly asked his officials to tell his subjects that the king
looked upon them as his children. As agents of the king, the officials were also
asked to take care of the people. Ashoka appointed dhammamahamatras to
propagate dharma among various social groups, including women, and
appointed rajukas for the administration of justice in his empire.
Ashoka disapproved of rituals, especially those observed by women. He forbade killing certain birds and animals, prohibited the slaughter of animals in
the royal kitchen, and forbade the slaughter of animals in sacrifices. He banned
gay social functions in which people indulged in an excess of revelry.
--------------------------------------------------
{'chapter': 'Modern Historians of Ancient India', 'chapter_chunk': 6, 'chunk_label': 'Modern Historians of Ancient India_6', 'chunk_level': 'Chapter2_6'}
observations appeared to have some validity. Thus, in comparison to the
Chinese, Indians did not show any strong sense of chronology although in the
earlier stage, important events were dated with reference to the death of Gautama
Buddha. However, generalizations made by colonialist historians were by and
large either false or grossly exaggerated, but served as good propaganda material
for the perpetuation of the despotic British rule. Their emphasis on the Indian tradition of one-man rule could justify the system which vested all powers in the
hands of the viceroy. Similarly, if Indians were obsessed with the problems of
the next world, the British colonial masters had no option but to look after their
life in this world. Without any experience of self-rule in the past, how could the
natives manage their affairs in the present? At the heart of all such
generalizations lay the need to demonstrate that Indians were incapable of
governing themselves.
--------------------------------------------------
{'chapter': 'The Maurya Age', 'chapter_chunk': 9, 'chunk_label': 'The Maurya Age_9', 'chunk_level': 'Chapter18_9'}
pay for it. In addition, in times of emergency, peasants were compelled to raise
more crops. Tolls were also levied on commodities brought to town for sale, and
they were collected at the gate. Moreover, the state enjoyed a monopoly in
mining, sale of liquor, manufacture of arms, etc. This naturally brought vast resources to the royal exchequer. Chandragupta thus established a well-
organized administrative system and gave it a sound financial base.
Ashoka (273–32 BC)
Chandragupta Maurya was succeeded by Bindusara, whose reign is important
for its continuing links with the Greek princes. His son, Ashoka, is the greatest
of the Maurya rulers. According to Buddhist tradition, he was so cruel in his
early life that he killed his ninety-nine brothers to win the throne. However, as
this statement is based on a legend, it may be mythical. Ashoka’s biography,
written by Buddhist authors, is so full of fiction that it cannot be taken seriously.
Ashokan Inscriptions
--------------------------------------------------
{'chapter': 'From Ancient to Medieval', 'chapter_chunk': 10, 'chunk_label': 'From Ancient to Medieval_10', 'chunk_level': 'Chapter31_10'}
the object in such cases was not only to win the favour of the king but also to
validate and exalt his position in the eyes of his rivals and subjects.
Chronology
(AD)

5 C
Foundation of the Buddhist structural complex at
Nalanda. Establishment of white Huna supremacy over
Kashmir, Punjab, and western India.
6 C
The Guptas ruled over north and western India for
about 160 years until the middle of the century.
606–47
The reign of Harshavardhana.
629
Hsuan Tsang left China for India.
645
Hsuan Tsang’s return to China.
670
The Chinese pilgrim I-tsing visited Nalanda.
7 C
Harshacharita by Banabhatta and Hsuan Tsang’s
account. 28
Brahmanization, Rural Expansion,
and Peasant Protest in the Peninsula
The New Phase
The period c. AD 300–750 marks the second historical phase in the regions south
of the Vindhyas. It continued some of the processes that had begun in the first
historical phase (c. 200 BC–AD 300) of the peninsula. It however shows some
--------------------------------------------------

In [ ]:
def rag_app(inputs):
    query = inputs["question"]

    docs = retriever.get_relevant_documents(query)

    return {
        "answer": llm.invoke(query),
        "retrieved_chunks": [d.page_content for d in docs]
    }

In [24]:
golden_df.head()

,ID,Question,Ground Truth Chunk,Reference Answer,Gold_Chunk
0,1,Why is it important to study the history of An...,Chapter_1,The study of ancient Indian history is importa...,[Chapter1_1]
1,2,What was the role of Sir William Jones?,Chapter_2,Sir William Jones was a civil servant of East ...,"[Chapter2_1, Chapter2_2]"
2,3,How did the Rationalist approach the History?,Chapter_2,A section of the Indian scholars tries to refo...,"[Chapter2_7, Chapter2_8, Chapter2_17]"
3,4,Who was Ramakrishna Gopal Bhandarkar and what ...,Chapter_2,Ramakrishna Gopal Bhandarkar was a Indian Hist...,"[Chapter2_8, Chapter2_9]"
4,5,How are prehistoric sites are different from h...,Chapter_3,There are several difference between prehistor...,[Chapter3_1]

In [25]:
from tqdm import tqdm
evaluation_results = []

for _, row in tqdm(golden_df.iterrows()):

    query = row["Question"]
    gold_chunks = row["Gold_Chunk"]

    results = retriever.invoke(query, k=5)

    retrieved_chunks = [
        doc.metadata["chunk_level"]
        for doc in results
    ]

    metrics = evaluate_retrieval(
        gold_chunks,
        retrieved_chunks
    )

    evaluation_results.append({
        "Question": query,
        "Gold_Chunks": gold_chunks,
        "Retrieved_Chunks": retrieved_chunks,
        "Recall@1": metrics["Recall@1"],
        "Recall@2": metrics["Recall@2"],
        "Recall@3": metrics["Recall@3"],
        "Recall@5": metrics["Recall@5"],
        "RR": metrics["RR"]
    })

50it [00:04, 10.97it/s]

In [26]:
eval_df = pd.DataFrame(evaluation_results)

print("===== Retrieval Metrics =====")
print(f"Recall@1 : {eval_df['Recall@1'].mean():.3f}")
print(f"Recall@2 : {eval_df['Recall@2'].mean():.3f}")
print(f"Recall@3 : {eval_df['Recall@3'].mean():.3f}")
print(f"Recall@5 : {eval_df['Recall@5'].mean():.3f}")
print(f"MRR       : {eval_df['RR'].mean():.3f}")

===== Retrieval Metrics =====
Recall@1 : 0.340
Recall@2 : 0.477
Recall@3 : 0.530
Recall@5 : 0.737
MRR       : 0.616

In [27]:
failures = eval_df[eval_df["Recall@5"] < 0.5]

failures[
    [
        "Question",
        "Gold_Chunks",
        "Retrieved_Chunks",
        "Recall@5"
    ]
]

,Question,Gold_Chunks,Retrieved_Chunks,Recall@5
2,How did the Rationalist approach the History?,"[Chapter2_7, Chapter2_8, Chapter2_17]","[Chapter33_7, Chapter2_17, Chapter2_14, Chapte...",0.333333
10,How ancient Indians view the rivers?,[Chapter5_10],"[Chapter1_10, Chapter4_10, Chapter2_16, Chapte...",0.000000
12,Tell me about the Indo-Aryan language group,"[Chapter6_7, Chapter6_8]","[Chapter6_1, Chapter6_9, Chapter12_54, Chapter...",0.000000
16,How was the agriculture of Neolithic setllers?,"[Chapter8_2, Chapter8_5, Chapter8_9]","[Chapter8_11, Chapter12_85, Chapter8_9, Chapte...",0.333333
18,What was the food of the Chalcolithc communities?,"[Chapter9_7, Chapter9_8]","[Chapter12_93, Chapter9_21, Chapter12_108, Cha...",0.000000
22,Role of War Chariot in Indo-European culture,[Chapter12_172],"[Chapter12_174, Chapter12_193, Chapter12_194, ...",0.000000
29,Who was Gautama Buddha?,"[Chapter14_21, Chapter14_20, Chapter_22]","[Chapter14_21, Chapter14_22, Chapter14_11, Cha...",0.333333
36,What were the names of the republic states dur...,[Chapter17_24],"[Chapter31_11, Chapter24_6, Chapter28_2, Chapt...",0.000000
39,What was the official language of the Satavaha...,[Chapter21_21],"[Chapter31_14, Chapter28_4, Chapter21_19, Chap...",0.000000
42,What was the capital of Harsha?,[Chapter26_25],"[Chapter26_27, Chapter26_24, Chapter15_3, Chap...",0.000000
49,What are the Buddhists sites in Afghanistan?,[Chapter31_4],"[Chapter31_54, Chapter31_5, Chapter31_53, Chap...",0.000000

## LLM as Judge for evaluation of Answer

In [73]:
from langchain_openai import ChatOpenAI
from langsmith import traceable
import json
import re


def safe_json_parse(text):
    try:
        return json.loads(text)
    except:
        match = re.search(r"\{.*\}", text, re.S)
        if match:
            try:
                return json.loads(match.group())
            except:
                pass

        return {
            "correctness": 0,
            "faithfulness": 0,
            "relevance": 0,
            "completeness": 0,
            "overall_score": 0,
            "reason": "parse_failed"
        }


@traceable(name="llm_judge")
def evaluate_answer(
    question: str,
    gold_answer: str,
    generated_answer: str,
    retrieved_context: str,
    model: str = "gpt-4o-mini"   # safer default
):

    prompt = f"""
You are an expert RAG evaluator.
As per the following guidelines:
1. correctness (1-5)
Measures whether the generated answer is factually correct compared to the gold answer and retrieved context.
2. faithfulness (1-5)
Measures whether the answer is strictly grounded in the retrieved context (no hallucination).
3. relevance (1-5)
Measures how well the answer addresses the user’s question.
4. completeness (1-5)
Measures whether the answer covers all key aspects needed to fully answer the question.
5. overall_score (float)
Weighted or holistic score (0–5) reflecting overall quality across all dimensions.


Return ONLY valid JSON:

{{
    "correctness": 1-5,
    "faithfulness": 1-5,
    "relevance": 1-5,
    "completeness": 1-5,
    "overall_score": float,
    "reason": "short explanation"
}}

Question:
{question}

Reference Answer:
{gold_answer}

Retrieved Context:
{retrieved_context}

Generated Answer:
{generated_answer}
"""

    llm = ChatOpenAI(model=model, temperature=0)

    response = llm.invoke(prompt)

    return safe_json_parse(response.content)

In [55]:
# test with one
question = "Write detailed description of the Mohenjo-daro bath"
golden_answer = golden_df.loc[golden_df['Question'] == question, 'Reference Answer'].values[0]
generated_answer = generate_answer(question)
context_results = retriever.invoke(question, k=5)
retrieved_context = "\n".join([r.page_content for r in context_results])

metrics = evaluate_answer(
    question=question,
    gold_answer=golden_answer,
    generated_answer=generated_answer,
    retrieved_context=retrieved_context
)

<REDACTED>

In [ ]:

evaluation_results = []

for idx, row in golden_df.iterrows():

    question = row["Question"]
    golden_answer = row["Reference Answer"]

    # Generate RAG answer
    generated_answer,retrieved_context = generate_answer(question)

    # Adjust if your chain returns a dict
    if isinstance(generated_answer, dict):
        generated_answer = generated_answer["answer"]

    # Retrieve context used for evaluation
    docs = retriever.invoke(question, k=5)

    retrieved_context = "\n\n".join(
        doc.page_content for doc in docs
    )

    # LLM Judge
    metrics = evaluate_answer(
        question=question,
        gold_answer=golden_answer,
        generated_answer=generated_answer,
        retrieved_context=retrieved_context
    )

    evaluation_results.append({
        "Question": question,
        "Correctness": metrics["correctness"],
        "Faithfulness": metrics["faithfulness"],
        "Relevance": metrics["relevance"],
        "Completeness": metrics["completeness"],
        "Overall": metrics["overall_score"],
        "Reason": metrics["reason"]
    })

    print(
        f"{idx+1}/{len(golden_df)} | "
        f"Overall={metrics['overall_score']}"
    )

# Create results dataframe
eval_df = pd.DataFrame(evaluation_results)

1/50 | Overall=4.75
2/50 | Overall=5.0
3/50 | Overall=1.0
4/50 | Overall=4.25
5/50 | Overall=4.0
6/50 | Overall=4.75
7/50 | Overall=4.0
8/50 | Overall=4.75
9/50 | Overall=1.0
10/50 | Overall=4.75
11/50 | Overall=4.75
12/50 | Overall=3.5
13/50 | Overall=3.5
14/50 | Overall=4.75
15/50 | Overall=5.0
16/50 | Overall=5.0
17/50 | Overall=4.75
18/50 | Overall=4.25
19/50 | Overall=4.25
20/50 | Overall=5.0
21/50 | Overall=1.0
22/50 | Overall=5.0
23/50 | Overall=4.25
24/50 | Overall=4.5
25/50 | Overall=4.5
26/50 | Overall=4.75
27/50 | Overall=3.75
28/50 | Overall=4.5
29/50 | Overall=5.0
30/50 | Overall=5.0
31/50 | Overall=4.75
32/50 | Overall=5.0
33/50 | Overall=5.0
34/50 | Overall=4.75
35/50 | Overall=1.0
36/50 | Overall=4.0
37/50 | Overall=2.0
38/50 | Overall=4.75
39/50 | Overall=5.0
40/50 | Overall=5.0
41/50 | Overall=5.0
42/50 | Overall=4.25
43/50 | Overall=1.0
44/50 | Overall=4.5
45/50 | Overall=4.75
46/50 | Overall=5.0
47/50 | Overall=5.0
48/50 | Overall=4.5
49/50 | Overall=5.0
50/50 | Overall=4.75

In [65]:
eval_df

,Question,Correctness,Faithfulness,Relevance,Completeness,Overall,Reason
0,Why is it important to study the history of An...,5,5,5,4,4.75,The answer accurately captures the main reason...
1,What was the role of Sir William Jones?,5,5,5,5,5.00,The answer accurately reflects the retrieved c...
2,How did the Rationalist approach the History?,1,1,1,1,1.00,Response is blank ('I don't know') and does no...
3,Who was Ramakrishna Gopal Bhandarkar and what ...,5,4,5,3,4.25,Accurately describes who Bhandarkar was and hi...
4,How are prehistoric sites are different from h...,4,4,5,3,4.00,Accurate core distinctions (prehistory vs hist...
5,How history of climate and vegetations are stu...,5,5,4,5,4.75,Core claim (pollen analysis for climate/vegeta...
6,Summarize Sangam Literature as a historical so...,4,4,5,3,4.00,Covers core facts (Sangam college under royal ...
7,Describe the creation of India as a geographic...,5,5,5,4,4.75,Covers the main creation timeline and geograph...
8,What are the major rivers in India?,1,1,1,1,1.00,The answer provides no information about the m...
9,Where are Copper mines located in India?,5,5,5,4,4.75,Accurately states the main locations (Chhotana...
10,How ancient Indians view the rivers?,5,5,4,5,4.75,Accurately states rivers were viewed as divine...
11,How did Dravidian language migrated south?,3,5,4,2,3.50,The answer correctly states the migration rout...
12,Tell me about the Indo-Aryan language group,4,4,4,2,3.50,The answer correctly notes Indo-Aryan as a maj...
13,Write a short note on Homo Habilis,5,4,5,5,4.75,"Covers core facts: meaning, timeframe, geograp..."
14,Where was the first human fossil found in Indi...,5,5,5,5,5.00,Accurately states Siwalik hills as the locatio...
15,Where is Mehrgarh loacated?,5,5,5,5,5.00,Answer provides the exact location: Baluchista...
16,How was the agriculture of Neolithic setllers?,5,5,5,4,4.75,"Accurately describes crops (wheat, barley, rag..."
17,Write a short note on the Chalcolithic arts an...,4,4,5,4,4.25,"Accurate coverage of copper-work, bead imports..."
18,What was the food of the Chalcolithc communities?,4,4,5,4,4.25,Covers major components of Chalcolithic food (...
19,Write detailed description of the Mohenjo-daro...,5,5,5,5,5.00,The answer accurately captures all the key fac...
20,Explain the Yogi seal of Indus,1,1,1,1,1.00,The answer provides no information about the Y...
21,Tell me about the Harappan script,5,5,5,5,5.00,The answer accurately restates the known facts...
22,Role of War Chariot in Indo-European culture,4,4,5,4,4.25,The answer accurately covers key points from t...
23,Tell me about the Horse Sacrifice in Vedic Cul...,4,5,5,4,4.50,"Core points (asvamedha, two Rig Veda hymns, In..."
24,"When did the Aryan migrate to india, write the...",4,5,5,4,4.50,Accurately reflects the debated timing (8000 B...
25,Tell about the Bharata clan,5,5,5,4,4.75,The answer accurately reflects the key points ...
26,Summarize Social Differentiation during Vedic ...,4,5,4,2,3.75,The generated answer correctly identifies key ...
27,Describe arts and crafts of the later vedic pe...,5,5,5,4,4.50,The answer accurately reflects the main points...
28,What were the five doctrines of Jainsim?,5,5,5,5,5.00,Accurately lists the five Jain doctrines exact...
29,Who was Gautama Buddha?,5,5,5,5,5.00,The answer accurately summarizes the key biogr...
30,What were the main philosophy of Buddhism?,5,5,5,4,4.75,The answer accurately summarizes the core Budd...
31,What led to large states?,5,5,5,5,5.00,The answer accurately reflects the retrieved c...
32,what was the capital of the kingdom of Kashi?,5,5,5,5,5.00,The answer correctly states Varanasi as the ca...
33,What area of Indian subcontinent was under the...,5,5,5,4,4.75,Accurately lists the Iranian-controlled area (...
34,Why did Alexandar not invade India?,1,1,1,1,1.00,The answer simply says 'I don't know' and does...
35,How was the Magadha army during the time of Al...,3,4,5,4,4.00,"Cavalry count differs from the reference (60,0..."
36,What were the names of the republic states dur...,1,5,1,1,2.00,The answer provides no information about the r...
37,What was the origin of Chandragupta Maurya?,5,5,5,4,4.75,Accurately reflects the origin claims from bot...
38,How was the King Ashoka referred in his inscri...,5,5,5,5,5.00,Answer correctly identifies devanampiya piyada...
39,What was the official language of the Satavaha...,5,5,5,5,5.00,Answer correctly states Prakrit as the officia...
40,what were the main kingdoms of the south India...,5,5,5,5,5.00,"Accurately names the Chola, Pandya, and Chera ..."
41,Explain the conquest of King Samudragupta,4,5,5,3,4.25,Accurately captures the five-group framework a...
42,What was the capital of Harsha?,1,1,1,1,1.00,The reference answer states Kanauj as the capi...
43,How was the law and order during Harsha's time?,4,5,5,4,4.50,The answer captures the main points from the r...
44,Explain the Samkhya philosophy,5,5,5,4,4.75,The answer accurately describes Samkhya as a s...
45,How one can attain salvation as per Yoga school?,5,5,5,5,5.00,The answer accurately reflects Yoga school's p...
46,What is the largest Buddhist temple in the world?,5,5,5,5,5.00,Answer correctly identifies Borobudur as the l...
47,What does Bhakti mean?,4,5,5,4,4.50,The answer captures the core meaning of Bhakti...
48,What was Vaisheshika?,5,5,5,5,5.00,Generated answer accurately reflects the retri...
49,What are the Buddhists sites in Afghanistan?,5,5,5,4,4.75,Accurately lists Begram and Bamiyan as Buddhis...

In [66]:
eval_df[[
    "Correctness",
    "Faithfulness",
    "Relevance",
    "Completeness",
    "Overall"
]].mean()

Correctness     4.200
Faithfulness    4.420
Relevance       4.420
Completeness    3.800
Overall         4.205
dtype: float64

In [69]:
summary = {
    "Correctness": eval_df["Correctness"].mean(),
    "Faithfulness": eval_df["Faithfulness"].mean(),
    "Relevance": eval_df["Relevance"].mean(),
    "Completeness": eval_df["Completeness"].mean(),
    "Overall": eval_df["Overall"].mean(),
    # "Pass_Rate": eval_df["Pass"].mean()
}

summary

{'Correctness': np.float64(4.2),
 'Faithfulness': np.float64(4.42),
 'Relevance': np.float64(4.42),
 'Completeness': np.float64(3.8),
 'Overall': np.float64(4.205)}

In [3]:
from langsmith import traceable

@traceable
def generate_answer(question):
    return "test answer"

generate_answer("test")

'test answer'

# Langsmith Evaluation

In [56]:
def rag_app(inputs: dict):
    question = inputs["Question"]

    context_results = retriever.invoke(question, k=5)
    retrieved_context = "\n\n".join(
        doc.page_content for doc in context_results
    )
    answer = generate_answer(question)

    return {
        "answer": answer,
        "context": retrieved_context
    }

In [57]:
JUDGE_CACHE = {}



# ----------------------------
# 1. CACHE METRICS (IMPORTANT OPTIMIZATION)
# ----------------------------
def get_metrics_once(run, example):

    cache_key = run.id

    if cache_key not in JUDGE_CACHE:

        JUDGE_CACHE[cache_key] = evaluate_answer(
            question=example.inputs["Question"],
            gold_answer=example.outputs["Reference Answer"],
            generated_answer=run.outputs["answer"],
            retrieved_context=run.outputs["context"]
        )

    return JUDGE_CACHE[cache_key]

# ----------------------------
# 2. LANGSMITH EVALUATORS (NO LLM CALLS HERE)
# ----------------------------
def correctness_evaluator(run, example):
    m = get_metrics_once(run, example)
    return {"key": "correctness", "score": m["correctness"]}


def faithfulness_evaluator(run, example):
    m = get_metrics_once(run, example)
    return {"key": "faithfulness", "score": m["faithfulness"]}


def relevance_evaluator(run, example):
    m = get_metrics_once(run, example)
    return {"key": "relevance", "score": m["relevance"]}


def completeness_evaluator(run, example):
    m = get_metrics_once(run, example)
    return {"key": "completeness", "score": m["completeness"]}

In [76]:
# ----------------------------
# 3. RUN LANGSMITH EVALUATION
# ----------------------------
from langsmith import Client

client = Client()

results = client.evaluate(
    rag_app,
    data="ancient_rag",
    evaluators=[
        correctness_evaluator,
        faithfulness_evaluator,
        relevance_evaluator,
        completeness_evaluator,
    ],
    experiment_prefix="rag-v2-highT"
)

View the evaluation results for experiment: 'rag-v2-highT-6636583c' at:
https://smith.langchain.com/o/a7df2e3a-7089-4e7a-b50e-dfaf56d72201/datasets/77502e77-588a-4664-a54d-a1f4a04d7bcf/compare?selectedSessions=0a072647-f610-43aa-a67a-65951548812d

50it [03:43,  4.47s/it]

In [61]:
print("JUDGE OUTPUT:", m)

JUDGE OUTPUT: <re.Match object; span=(12730, 12768), match='33.\nLegacy in Science and Civilization'>

In [77]:
from langsmith import traceable

@traceable(name="retrieval")
def retrieve_docs(query):
    docs = retriever.invoke(query, k=5)
    return docs

In [96]:
def rag_app_ret(inputs):
    query = inputs["Question"]

    docs = retriever.invoke(query)
    answer = generate_answer(query)

    

    return {
        "answer": answer,
        "retrieved_chunks": [d.page_content for d in docs],
        "chunk_level": [d.metadata['chunk_level'] for d in docs]
    }

In [97]:

@traceable(name="retrieval_metrics")
def evaluate_retrieval(run, example):

    retrieved_chunks = set(run.outputs["chunk_level"])

    gold_chunks = set(example.outputs["gold_chunks"])

    metrics = {}

    # Recall@K
    for k in [1, 2, 3, 5]:
        top_k = set(retrieved_chunks[:k])
        hits = len(gold_chunks & top_k)
        metrics[f"Recall@{k}"] = hits / len(gold_chunks)

    # Reciprocal Rank (MRR per query)
    rr = 0.0
    for rank, chunk in enumerate(retrieved_chunks, start=1):
        if chunk in gold_chunks:
            rr = 1 / rank
            break

    metrics["RR"] = rr

    return metrics

In [110]:
def evaluate_retrieval(run, example):

    retrieved = run.outputs["chunk_level"]
    gold = example.outputs["Gold_Chunk"]
    # print(retrieved)
    # print(gold)

    retrieved_set = set(retrieved)
    gold_set = {x.strip() for x in gold.split(",")}

    intersection = retrieved_set & gold_set
    # print(intersection)

    # Recall@K
    recall = (
        len(intersection) / len(gold_set)
        if gold_set else 0
    )

    # Precision@K
    precision = (
        len(intersection) / len(retrieved_set)
        if retrieved_set else 0
    )

    # F1@K
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0 else 0
    )

    # Hit Rate
    hit_rate = 1 if len(intersection) > 0 else 0

    # MRR
    mrr = 0
    for rank, chunk_id in enumerate(retrieved, start=1):
        if chunk_id in gold_set:
            mrr = 1 / rank
            break

    return {
        "results": [
            {"key": "Recall@K", "score": recall},
            {"key": "Precision@K", "score": precision},
            {"key": "F1@K", "score": f1},
            {"key": "HitRate@K", "score": hit_rate},
            {"key": "MRR", "score": mrr},
        ]
    }

In [111]:
from langsmith import evaluate

results = evaluate(
    rag_app_ret,
    data="ancient_rag",
    evaluators=[evaluate_retrieval],
    experiment_prefix="rag-retrieval-metrics"
)

View the evaluation results for experiment: 'rag-retrieval-metrics-1aa41e53' at:
https://smith.langchain.com/o/a7df2e3a-7089-4e7a-b50e-dfaf56d72201/datasets/77502e77-588a-4664-a54d-a1f4a04d7bcf/compare?selectedSessions=7b40d6dd-4b63-4602-9da0-bfcc2e852a12

50it [02:24,  2.89s/it]